the-convocation/twitter-scraper

src/scraper.ts
src/tweets.test.ts
src/tweets.ts

Just a small pull that adds an easier way to get the latest tweet, with an `includeRetweets` parameter included.
I have tested it on my end via Jest and can confirm it works.
```ts
test('scraper can get latest tweet', async () => {
const scraper = new Scraper();
// OLD APPROACH (without retweet filtering)
const tweets = scraper.getTweets('elonmusk', 1, false);
const expected = (await tweets.next()).value;
// NEW APPROACH
const latest = await scraper.getLatestTweet('elonmusk', false, false);
expect(expected.permanentUrl).toEqual(latest?.permanentUrl);
});
```

Implement `getLatestTweet()` in tweets.ts

---

package.json
src/api.ts
src/scraper.ts
typedoc.json

- use `typedoc.json` to build docs instead of a long script.
- slight documentation edits inside "scraper.ts" file.
- document `requestApi` method, including internal tag.
- exclude files beginning with an underscore from documentation, this will remove `_module.html` which only contains 404s.

Documentation improvements.

---

README.md

Twitter has added a number of restrictions to their API that render the original package description outdated. This adds some known limitations underneath it.

chore: add new known limitations to README

---

README.md
src/api.ts
src/scraper.ts
src/tweets.test.ts
typedoc.json

Heyo, me again 👋🏼 
- removed both tokens in favour of new, updated one used by nitter.
- implemented cleaner `useGuestAuth` method used by both constructor and `logout`.
- created a new test to ensure tweets are fetched without logging in.
- running latest tweet test now uses regular scraper instead of `authSearchScraper`.
**Note**:
Nitter also changed some features and graphql endpoints, but I'm not familiar with them so they were not included.
See [this commit](https://github.com/zedeus/nitter/pull/927/commits/d1f80446ef9c3c78b41572382d34812eb5131b27#diff-5191c99e8da841954d23cae0097143d48f54b50737f8ef7b8b7ef2fabdd2dcd6)

fix: update bearer token

---

src/timeline-v2.ts
src/tweets.test.ts

The following properties on the `Tweet` interface are now `false` as default. 
This most likely fixes any methods that caused issues as a result of checking any of these.
- `isQuoted`
- `isRetweet`
- `isReply`
- `isPin`
- `sensitiveContent`
Tweet tests have been updated accordingly.

fix some Tweet properties defaulting to undefined.

---

src/scraper.ts
src/tweets.test.ts
src/tweets.ts

- implement `getTweetWhere`. Gets the first tweet matching the query, or null if no match.
- implement `getTweetsWhere`. An array of all tweets matching the query (or empty).
- support passing optional `max` variable to `getLatestTweet`.
Tests and documentation included for both new methods.

feat: utility methods for fetching tweets using a query

---

src/api.ts
src/profile.ts
src/search.test.ts
src/search.ts
src/timeline-search.ts
src/timeline-v1.ts
src/timeline-v2.ts
src/tweets.ts

Ports the new GraphQL endpoints and parsing edits as seen [here](https://github.com/zedeus/nitter/commit/0bc3c153d9b38a3c02f321fb64a375fef6b97e8e).
**Notes**: 
- Implemented `isBlueVerified` and `mediaCount` on the `Profile` interface.
- Tweet `views` property no longer exists and so that test will fail - a solution is required to restore this.
- All other tests pass, but I cannot be sure every single method returns data as intended.
Fixes #34

Nitter graphql port

---

src/profile.ts

This MR allows profile parsing to return a full size avatar url instead of the `normal` size returned by default by the api.
API Reference: https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/user-profile-images-and-banners

feat(profile): provide original avatar size url

---

src/timeline-v2.ts
src/tweets.test.ts

Basically just removes `tweet-` and `conversation-` prefixes sometimes being included in the final tweet.

fix: tweet id prefix not being removed

---

.gitignore
src/timeline-tweet-util.ts
src/timeline-v1.ts
src/tweets.ts

The PR allows `parseMediaGroups` to parse the Tweet photos `ext_alt_text` prop and inject it in parsed `Photo`
Tips:
- `ext_alt_text` can be `string | undefined`
- media are already filtered on `id_str` and `media_url_https` being defined. Now, they are also generated with `ext_alt_text` that can be `undefined`.

feat: add photo alt text

---

src/timeline-search.ts
src/timeline-v1.ts
src/timeline-v2.ts

Previously only bottom cursors were parsed and returned. This prevents the library from being used for real-time scraping, as it can only iterate historical items in queries  with no way to fetch new results since the initial query. This patch adds a `previous` cursor to timeline responses.
Related: #54

feat(timeline): add low-level support for top cursors

---

src/profile.ts
src/tweets.ts

See #66. Choosing to change how the value is filled instead of removing it for backwards-compatibility.

fix: use friends_count for follower count

---

src/timeline-list.ts
src/timeline-v2.ts

This pull request fixes a problem of skipping replies to tweets in list timeline. Here the example of structure of reply in list:
.
This pull request was tested by checking fetchListTweets results in  my app and works well for me.

add list-conversation tweets support for fetchListTweets

---

src/profile.ts
src/timeline-async.ts

- Fix #69 
- Catch an error when trying to fetch profile of non-existent user
Problem for #69 was that it for whatever reason returned one empty page at some point even though the pages after that still contained results. Fixed by breaking from the loop only when there have been 5 consecutive empty pages (or the cursor to next page is undefined).

fix: getFollowers not returning all followers

---

package.json
src/scraper.ts
src/timeline-list.ts
src/timeline-v2.ts
src/tweets.test.ts
src/tweets.ts

Fixes #73.
Most timeline entries are `TimelineTimelineTweet` entries and just contain a tweet, but some entries are `TimelineTimelineModule` entries, such as profile conversations, which contain a set of tweets. This adds handling for the latter case.

Handle profile conversations in TimelineTimelineModule entries

---

package.json
src/auth-user.ts
src/auth.ts
src/scraper.ts
src/test-utils.ts
yarn.lock

this puts it more in line with what twscrape does and should be more resilient to upstream changes
2FA gets tested if a `TWITTER_2FA_TOKEN` is specified, but isn't otherwise.

refactor user auth & implement 2FA

---

src/timeline-v1.ts
src/timeline-v2.ts

Tweets that have limited replies (such as [1779717986082849241](https://twitter.com/sachi_sachiko/status/1779717986082849241))are not being parsed correctly, the object returned is of __typename 'TweetWithVisibilityResults' and contains a tweet property with the actual tweet. 
Once set the result to the tweet of the wrapped object, parsing seems to be performing good

fix: parse tweetwithvisibilityresults type

---

src/auth-user.ts

I discovered that sometimes twitter will ask for an alternate identifier (an email) to login when it detects suspicious activity, so I have added a method to the TwitterUserAuth class to handle it

Handling 'LoginEnterAlternateIdentifierSubtask'

---

src/timeline-v1.ts
src/timeline-v2.ts
src/tweets.test.ts
src/tweets.ts

Adds a new `__raw_UNSTABLE` property on Tweet objects with the original tweet. This should help with both extracting more data than the scraper typically provides, reprocessing the original data in a different way, and simple debugging. No compatibility guarantees are currently made for this field.

feat: include raw tweet as part of results

---

src/timeline-search.ts
src/timeline-v1.ts
src/timeline-v2.ts
src/tweets.test.ts
src/tweets.ts

#94 
Adds `isEdited` and `versions` properties to the Tweet object, which will be `undefined` if they cannot be retrieved. `versions` contains all tweet versions (including the current one), while `isEdited` is true if `versions` has more than one element.

feat: tweet edit information

---

.prettierignore
README.md
package.json
src/_module.ts
src/api-types.ts
src/api.ts
src/auth.ts
src/rate-limit.ts
src/scraper.test.ts
src/scraper.ts
typedoc.json
yarn.lock

Implements support for custom rate-limiting strategies, allowing for changing the default library behavior of waiting until the current period has expired. This allows for significantly more flexibility in how rate-limiting is handled, and also enables library consumers to define their own implementations that do monitoring and/or logging when rate-limiting occurs by implementing `RateLimitStrategy` themselves.
This also adds a new implementation of this strategy that simply throws an error when being rate-limited:
```ts
import { Scraper, ErrorRateLimitStrategy } from "@the-convocation/twitter-scraper";
const scraper = new Scraper({
rateLimitStrategy: new ErrorRateLimitStrategy(),
});
```
---
**On pooling (tl;dr not yet but now you can DIY it)**
One of the primary desired use cases for …

feat: support custom rate-limiting strategies

---

jest.config.js
src/_module.ts
src/auth-user.test.ts
src/auth-user.ts
src/auth.ts
src/errors.ts
src/relationships.ts
src/scraper.ts
src/search.ts
src/tweets.ts

Implements support for registering custom auth subtasks, particularly so that consumers can handle the `ArkoseLogin` subtask however is most appropriate for their target platform ([examples](https://github.com/search?q=ArkoseLogin&type=code)). The API also permits overriding existing subtasks, in the event that consumers want to replace any of the existing implementation.
The subtask handler API is shown below:
```ts
type FlowSubtaskHandler = (subtaskId: string, previousResponse: TwitterUserAuthFlowResponse, credentials: TwitterUserAuthCredentials, api: FlowSubtaskHandlerApi) => Promise<FlowTokenResult>;
interface FlowSubtaskHandlerApi {
/**
* Send a flow request to the Twitter API.
* @param request The request object containing flow token and subtask inputs
* @returns The result of the …
```

Support custom auth subtask registration

---

src/timeline-v2.ts

isEdited was always false if tweet was edited only once because editsIds contains only the edited tweet id
Remove editsIds and use tweetVersions, length need to be > 1 because original tweet id is always present
Exemple : This tweet was flag to not edited but it contain more 1 edit (the original tweet) https://x.com/DOFUSfr/status/1925960820732592438

Fix: isEdited was always false if tweet was edited only once

---

package.json
src/timeline-v1.ts
src/timeline-v2.test.ts
src/timeline-v2.ts

Pinned tweets come in an instruction under an `entry` key, not an `entries` key like regular tweets, so they were getting silently ignored. This PR collapses single entry instructions into the full instruction list we consume.
Fixes #135.

Parse user pinned tweets correctly

---

src/timeline-tweet-util.ts
src/timeline-v1.ts
src/tweets.test.ts

This PR fixes the bug that causes the .mp4 to not be returned when a GIF is present in a tweet.
Added a [`parseGif`](https://github.com/Faareoh/twitter-scraper/blob/47ff38725d8e80a5628dc64233f996fac226f5d2/src/timeline-tweet-util.ts#L46) function in `timeline-tweet-utils`.
Updated the `VideoVariant` interface to add the [`content_type`](https://github.com/Faareoh/twitter-scraper/blob/47ff38725d8e80a5628dc64233f996fac226f5d2/src/timeline-v1.ts#L35) field.
Updated the [corresponding test](https://github.com/Faareoh/twitter-scraper/blob/47ff38725d8e80a5628dc64233f996fac226f5d2/src/tweets.test.ts#L397).

Fix gif parsing to correctly get the .mp4 url
